spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookstore
    username: root
    password: Vivian2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
