spring:
  datasource:
    url: jdbc:mariadb://bookstore-db:3306/bookstore  # ✅ MariaDB 內部名稱
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis
    port: 6379


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

