spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookstore
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

